config/routes.rb
Rails.application.routes.draw do
	root "categories#index"

  resources :sessions
  resources :users

  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  resources :categories, only: [:index,:show] do
    resources :games, only: [:index, :show]
  end

  post '/games/:id/upvotes' => 'games#upvote', as: :game_upvote
  post '/games/:id/downvotes' => 'games#downvote', as: :game_downvote
  # Handling comments, follows, votes
  shallow do
    resources :games, only: [] do
      resources :comments
      resources :subscriptions
    end
  end
  post '/comments/:id/upvotes' => 'comments#upvote', as: :comment_upvote
  post '/comments/:id/downvotes' => 'comments#downvote', as: :comment_downvote

  post '/follows/:id' => 'follows#user', as: :follows_user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :games

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :votes, as: :voteable


  # Return total number of votes by summing up values of vote objects
  def vote_total
    if self.votes.length > 0
      self.votes.reduce(0){|sum, vote| sum + vote.value}
    else
      self.votes.length
    end
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :followed_user, class_name: "User"
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :category
  has_many :subscriptions
  has_many :followers, through: :subscriptions, source: :user
  has_many :comments
  has_many :votes, as: :voteable

  validates :title, :description, presence: true

  # Return total number of votes by summing up values of vote objects
  def vote_total
    if self.votes.length > 0
      self.votes.reduce(0){|sum, vote| sum + vote.value}
    else
      self.votes.length
    end
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  has_many :votes
  has_many :games, through: :subscriptions
  has_many :comments
  has_many :subscriptions
  has_many :follows
  has_many :followers, through: :follows, foreign_key: :followed_user, source: :followed_user
  has_secure_password
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :user_id, :scope => [:voteable_type, :voteable_id]
  validates :value, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :login, :logout, :current_subscription

  def index
    @parallax = true
  end

  def login(user)
  	session[:user_id] = user.id
  end

  def logout
  	session[:user_id] = nil
  end

  def current_user
  	if session[:user_id]
  		User.find(session[:user_id])
  	else
  		nil
  	end
  end

  # def subscribed?(user, game)
  #   subscription = user.games.select{|game_ob| game_ob.id == game.id}
  #   if subscription.length > 0
  #     true
  #   else
  #     false
  #   end
  # end
  def current_subscription(game)
    subscription = current_user.games.select{|game_ob| game_ob.id == game.id}
    # subscription.first
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @parallax = true
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comment = Comment.find(id: params[:id])
  end
  # post
  def create
    @game = Game.find(params[:game_id])
    if current_user
      @comment = @game.comments.new(body: params[:comment], user_id: current_user.id)
      if @comment && @comment.save
        redirect_to category_game_path(@game.category, @game)
      else
        flash[:notice] = "comment error"
        redirect_to category_game_path(@game.category, @game)
      end
    else
      flash[:notice] = "You must be logged in"
      redirect_to new_session_path
    end
  end

  #put a comment
  def update
  end
  #delete a comment
  def destroy
    @comment = Comment.find(params[:id])
    @game = @comment.game
    @comment.destroy
    redirect_to category_game_path(@game.category, @game)
  end

  def upvote
    @comment = Comment.find(params[:id])
    @game = @comment.game
    if current_user
      @comment.votes.create(user_id: current_user.id, value: 1)
      redirect_to category_game_path(@comment.game.category, @comment.game)
    else
      flash[:notice] = "You must be logged in to use this feature"
      render 'games/show'
    end
  end

  def downvote
    @comment = Comment.find(params[:id])
    @game = @comment.game
    if current_user
      @comment.votes.create(user_id: current_user.id, value: -1)
      redirect_to category_game_path(@comment.game.category, @comment.game)
    else
      flash[:notice] = "You must be logged in to use this feature"
      render 'games/show'
    end
  end

  # show form to create a comment
  # def new
  # end
  #show form to edit comment
  # def edit
  # end
  #show a single comment
  # def show
  # end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def user
    p params
    p "***************"
    if current_user
      followed_user = User.find(params[:id])
      current_user.followers << followed_user
      redirect_to user_path(followed_user)
      
    else
      flash[:notice] = "You are already following this user"
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @category = Category.find(params[:id])
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def upvote
    @game = Game.find(params[:id])
    if current_user
      @game.votes.create(user_id: current_user.id, value: 1)
      redirect_to @game.category
    else
      flash[:notice] = "You must be logged in to use this feature"
      render 'show'
    end
  end

  def downvote
    @game = Game.find(params[:id])
    if current_user
      @game.votes.create(user_id: current_user.id, value: -1)
      redirect_to @game.category
    else
      flash[:notice] = "You must be logged in to use this feature"
      render 'show'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by(username: params[:username])
		if @user
			if @user.authenticate(params[:password])
				login(@user)
				redirect_to user_path(@user)
			end
		else
			render 'new'
		end 
	end 

	def destroy
		logout
		redirect_to root_path
	end

	# private
	# def session_params
	# 	session = {
	# 		username: params[:username],
	# 		password: params[:password]
	# 	}
	# 	# p params.require(:session).permit(:username)
	# end
end 

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
  end

  def create
    game = Game.find(params[:game_id])
    if current_user
      current_user.games << game
      redirect_to category_game_path(game.category, game)
    else
      redirect_to new_session_path
    end
  end

  def destroy
    if current_user
      subscription = Subscription.find(params[:id])
      game = subscription.game
      subscription.destroy
      redirect_to category_game_path(game.category, game)
    else
      redirect_to new_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		if current_user
			redirect_to user_path(current_user)
		else 
			@user = User.new
		end 
	end 

	def create
		@user = User.new(user_params)
		if @user.save
			login(@user)
			redirect_to user_path(@user)
		else
			render 'new'
		end 
	end 

	def show
		@user = User.find(params[:id])
		@followers = @user.followers
		@subscriptions = @user.games
    @a = 0
	end 

	private 
	def user_params
		params.require(:user).permit(:username, :password)
	end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/categories/_chessheader.html.erb
<div id="parallax" class="parallax-container">
    <div class="parallax"><%= image_tag "monopoly2.jpg" %></div>
  </div>
  <div class="section white">
    <div class="row container">
      <h2 class="header">GameBook</h2>
      <p class="grey-text text-darken-3 lighten-3">Know the game before the player. Don't hate the player, hate the game.</p>
    </div>
  </div>
  <!-- <div class="parallax-container">
    <div class="parallax"><img src="images/parallax2.jpg"></div>
  </div> -->

app/views/categories/index.html.erb
<%= render 'categories/chessheader' %>
<!-- <ul>
<% @categories.each do |category| %>
  <li><a href="<%= category_path(category) %>"><%= category.name %></a></li>
<% end %>
</ul> -->



<table class="striped responsive-table">
    <thead>
      <tr>
          <th data-field="id">Category</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @categories.each do |category| %>
          <td><a href="<%= category_path(category) %>"><%= category.name %></a></td>
        </tr>
        <% end %>
    </tbody>
  </table>

app/views/categories/show.html.erb
<div class="row">
<h2><%= @category.name %></h2>
<% @category.games.each do |game| %>
<div class="col m6">
  <div class="row card grey lighten-3">
    <div class="col m3">
      <p class="center"><a href="<%= game_upvote_path(game) %>" rel="nofollow" data-method="post" class="btn"><i class="large material-icons">thumb_up</i></a></p>
      <p class="center flow-text"><%= game.vote_total %></p>
      <p class="center"><a href="<%= game_downvote_path(game) %>" rel="nofollow" data-method="post" class="btn"><i class="large material-icons">thumb_down</i></a></p>
    </div>

    <div class="col m9">
      <a class="game-link" href="<%= category_game_path(@category, game) %>"><%= game.title %></a>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/comments/_form.html.erb
<div class="row">
<%= form_tag game_comments_path(@game) do %>
  <div class="col s9">Add a Comment: <%= text_field_tag :comment%></div>
  <div class="col s3"><%= submit_tag "Submit", :class => "btn" %></div>
<% end %>
</div>

app/views/games/_comments.html.erb
<% @game.comments.each do |comment| %>
  <!-- comment div-->
  <div class="comment">
    <!-- comment body-->
    <div class="row">
      <!-- Comment Vote Buttons -->
      <div class="col m2">

                <p class="center"><a href="<%= comment_upvote_path(comment) %>" rel="nofollow" data-method="post" class="btn"><i class="large material-icons">thumb_up</i></a></p>
                <p class="center flow-text"><%= comment.vote_total %></p>
                <p class="center"><a href="<%= comment_downvote_path(comment) %>" rel="nofollow" data-method="post" class="btn"><i class="large material-icons">thumb_down</i></a></p>

      </div>
      <!-- User Profile -->
      <div class="col m3">
        <% if current_user && current_user.id == comment.user_id %>
          <%= image_tag "max.jpg" %>
        <% else %>
          <%= image_tag "no_image.png" %>
        <% end %>
        <p><%= link_to comment.user.username, user_path(comment.user) %></p>
      </div>
      <!-- Comment Body -->
      <div class="col m7">
        <p>"<%=comment.body%>"</p>
        <% if current_user && current_user.id == comment.user_id %>
          <!-- <%= link_to "Edit", edit_comment_path(comment), method: "put", action:"update" %> | -->
          <%= link_to "Delete", comment_path(comment), method: "delete", action: "destroy" %>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
<% end %>

app/views/games/_subscribe.html.erb
<% if current_user && current_subscription(@game).length > 0 %>
  <%= button_to "Unsubscribe", subscription_path(current_subscription(@game).first), method: "delete", :class=> "btn-large red" %>
<% else %>
  <%= button_to "Subscribe", game_subscriptions_path(@game), :class=> "btn-large blue" %>
<% end %>

app/views/games/index.html.erb
<h1><%= @category.name %></h1>

<ul>
<% @games.each do |game| %>
  <li><a href="<%= category_game_path(game) %>"><%= game.title %></a></li>
<% end %>
</ul>

app/views/games/show.html.erb
<div class="row">
  <div class="col m9">
    <h1><%= @game.title %></h1>
  </div>
  <div class="col m3">
    <br><br>
    <%= render 'subscribe' %>
  </div>
</div>

<p>Number of subscribers <%= @game.followers.length %></p>
<p>Number of votes <%= @game.vote_total %> </p>
<p><%= @game.description %></p>



<h3>Comments</h3>
<%= render 'comments/form' %>
<%= render 'comments' %>

app/views/users/new.html.erb
<div>
	<% if flash[:notice] %>
		<div class="notice">
			<%= flash[:notice] %>
		</div>
	<% end %>

	<%=form_for @user do |f|%>
		<ul>
			<%@user.errors.full_messages.each do |error|%>
				<li><%=error%></li>
			<%end%>
		</ul>
		<br>
		<%=f.label :username%>
		<p><%=f.text_field :username, placeholder: "username"%></p>
		<p><%=f.label :password%></p>
		<p><%=f.password_field :password, placeholder: "password"%></p>
		<%=f.submit value: "CREATE ACCOUNT"%>
	<%end%>
</div>

app/views/users/show.html.erb
<% if current_user && @user == current_user%>
	<h1>Your Profile</h1>
	<%= image_tag "max.jpg" %>
<% else %>
	<h1>Welcome to <%= @user.username%>'s Profile</h1>
	<%= image_tag "no_image.png" %>


	<% if current_user %>
		<% current_user.followers.each do |user|%>
			<% if user.id == @user.id %>
				<% @a = 5 %>
			<% end %>
		<% end %>
	<% end %>

	<% if @a != 5 %>
			<%= button_to "Follow #{@user.username}", follows_user_path(params[:id]) %>
	<% else %>
			<%= "You are following #{@user.username}"%>
	<% end %>
<% end %>

<h3>Following</h3>

<% @followers.each do |follower|%>
<ul>
	<li><a href="<%= user_path(follower) %>"><%= follower.username%></a></li>
</ul>
<% end %>
<br>
<br>
<br>
<h3>Game Subscriptions</h3>
<% @subscriptions.each do |subscription| %>
	<ul>
		<li><a href="<%= category_game_path(subscription.category, subscription) %>"><%= subscription.title %></a></li>
	</ul>
<% end %>